# Generated by Django 3.1.1 on 2023-04-27 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='dest',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='source',
            new_name='pickup_point',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='dest',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='book',
            name='nos',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='nos',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='rem',
        ),
        migrations.AddField(
            model_name='bus',
            name='pickup_point',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
